config:
  info: "master branch,springcloud-config/config-dev.yml,version=8"
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      
    driver-class-name: org.gjt.mm.mysql.Driver        
    jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
